### ISSUE TITLE
definition de la structure des donnees

### ISSUE THREAD

**Issue by elouardyabderrahim** [elouardyabderrahim/real-time-analysis-of-film-reviews-with-Kafka-and-Memgraph#1]
unifier la forme des donnees.

**Comment by aminelfaquiri** [comment]
@elouardyabderrahim @Sefdine @omardbaa @azemoure-1 
I think I need your review on this part to merge it .

**Comment by elouardyabderrahim** [comment]
@aminelfaquiri  I think it is not necessary to save firstly in the csv file you can derectly save it as a json , you did a great work .
what do you think @Sefdine  @azemoure-1 @omardbaa

**Comment by aminelfaquiri** [comment]
@elouardyabderrahim yes you are right i will do that .

**Comment by aminelfaquiri** [comment]
@elouardyabderrahim the modification you insist is done
@azemoure-1 @omardbaa @Sefdine

**Comment by elouardyabderrahim** [comment]
gooood happy to hear that . :) @aminelfaquiri
